Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Models/ErrorViewModel.cs
using System;

namespace TabAuthentication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using TabAuthentication.Models;

namespace TabAuthentication.Controllers
{
    public class AuthenticationController : Controller
    {

        private readonly ILogger<AuthenticationController> _logger;

        private readonly IConfiguration Configuration;

        public AuthenticationController(ILogger<AuthenticationController> logger, IConfiguration configuration)
        {
            _logger = logger;
            Configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("SimpleAuthStart")]
        public ActionResult SimpleAuthStart()
        {
            ViewBag.ClientId = Configuration["SimpleClientId"].ToString();
            ViewBag.ResponseType = Configuration["ResponseType"].ToString();
            ViewBag.ResponseMode = Configuration["ResponseMode"].ToString();
            ViewBag.Resource = Configuration["Resource"].ToString();
            return View();
        }

        [Route("SimpleAuthEnd")]
        public ActionResult SimpleAuthEnd()
        {
            return View();
        }

        [Route("SimpleSuccess")]
        public ActionResult SimpleSuccess()
        {
            return View();
        }

        [Route("SimpleFailed")]
        public ActionResult SimpleFailed()
        {
            return View();
        }

        [Route("SilentAuthStart")]
        public ActionResult SilentAuthStart()
        {
            ViewBag.AuthStartClientId = Configuration["ClientId"].ToString();
            return View();
        }

        [Route("SilentAuthEnd")]
        public ActionResult SilentAuthEnd()
        {
            ViewBag.AuthEndClientId = Configuration["ClientId"].ToString();
            return View();
        }

    }
}

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using TabAuthentication.Models;
using System.IdentityModel.Tokens.Jwt;
using Newtonsoft.Json.Linq;
using System.Security.Claims;

namespace TabAuthentication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IConfiguration Configuration;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            Configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }


        [Route("SimpleSetUp")]
        public IActionResult SimpleSetUp()
        {
            return View();
        }

        [Route("ChooseAuth")]
        public IActionResult ChooseAuth()
        {
            return View();
        }

        [Route("SilentConfigureTab")]
        public IActionResult SilentConfigureTab()
        {
            ViewBag.ClientId = Configuration["ClientId"].ToString();
            return View();
        }

        [Route("SimpleConfigureTab")]
        public IActionResult SimpleConfigureTab()
        {
            ViewBag.ClientId = Configuration["SimpleClientId"].ToString();
            return View();
        }   

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public string ValidateToken(string validToken)
        {
            string decode = "";
            string value = "";

            var jwtHandler = new JwtSecurityTokenHandler();
            var jwtInput = validToken;

            //Check if readable token (string is in a JWT format)
            var readableToken = jwtHandler.CanReadToken(jwtInput);

            if (readableToken != true)
            {
                decode = "The token doesn't seem to be in a proper JWT format.";
            }

            if (readableToken == true)
            {
                var token = jwtHandler.ReadJwtToken(jwtInput);

                //Extract the headers of the JWT
                //var headers = token.Header;
                //var jwtHeader = "{";

                //foreach (var h in headers)
                //{
                //    jwtHeader += '"' + h.Key + "\":\"" + h.Value + "\",";
                //}

                //jwtHeader += "}";
                //decode = "Header:\r\n" + JToken.Parse(jwtHeader).ToString(Formatting.Indented);

                //Extract the payload of the JWT
                var claims = token.Claims;
                var jwtPayload = "{";
                foreach (Claim c in claims)
                {
                    jwtPayload += '"' + c.Type + "\":\"" + c.Value + "\",";
                }
                jwtPayload += "}";
                decode += jwtPayload;

                value = JToken.Parse(jwtPayload).ToString(Formatting.Indented);
            }

            return value;
        }
    }
}

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Views/Home/ChooseAuth.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    Please click on any of the authentication
</p>
<div style="height: 20px">
</div>
<div>
    <!-- Login button -->
    <button id="btnLogin" onclick="silentLogin()">Login to Silent</button>
</div>
<div style="height: 30px">
</div>
<div>
    <button id="btnLogin" onclick="simpleLogin()">Login to Simple Azure AD</button>
</div>

<script type="text/javascript">

        function silentLogin() {
            window.location.href = "@Url.Action("SilentConfigureTab", "Home")";
        }

        function simpleLogin() {
            window.location.href = "@Url.Action("SimpleConfigureTab", "Home")";
        }

</script>

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Views/Home/ConfigureTab.cshtml
<!--
// Copyright (c) Microsoft Corporation
// All rights reserved.
//
// MIT License:
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of this software and associated documentation files (the
// "Software"), to deal in the Software without restriction, including
// without limitation the rights to use, copy, modify, merge, publish,
// distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to
// the following conditions:
//
// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED ""AS IS"", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
// OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->

<html>
<head>
    <title>Silent Authentication Sample</title>
</head>
<body>
    <p>
        This sample demonstrates silent authentication in a Microsoft Teams tab.
    </p>
    <p>
        The tab will try to get an id token for the user silently, validate the token and show the profile information decoded from the token.
        The "Login" button will appear only if silent authentication failed.
    </p>

    <!-- Login button -->
    <button id="btnLogin" onclick="login()" style="display: none">Login to Azure AD</button>

    <!-- Result -->
    <p>
        <div id="divError" style="display: none"></div>
        <div id="divProfile" style="display: none">
            <div><b>Name:</b> <span id="profileDisplayName" /></div>
            <div><b>UPN:</b> <span id="profileUpn" /></div>
            <div><b>Object id:</b> <span id="profileObjectId" /></div>
        </div>
    </p>

    <script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha384-VC7EHu0lDzZyFfmjTPJq+DFyIn8TUGAJbEtpXquazFVr00Q/OOx//RjiZ9yU9+9m" crossorigin="anonymous"></script>

    <!-- Check before upgrading your ADAL version, as this sample depends on an internal function to authenticate silently -->
    <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.15/js/adal.min.js" integrity="sha384-lIk8T3uMxKqXQVVfFbiw0K/Nq+kt1P3NtGt/pNexiDby2rKU6xnDY8p16gIwKqgI" crossorigin="anonymous"></script>
    <script src="https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js"></script>
    <script type="text/javascript">
        microsoftTeams.initialize();

        // ADAL.js configuration
        let config = {
            clientId: '@ViewBag.ClientId',
            redirectUri: window.location.origin + "/AuthEnd",       // This should be in the list of redirect uris for the AAD app
            cacheLocation: "localStorage",
            navigateToLoginRequestUrl: false,
        };

        let upn = undefined;
        microsoftTeams.getContext(function (context) {
            upn = context.upn;
            loadData(upn);
        });

        // Loads data for the given user
        function loadData(upn) {
            // Setup extra query parameters for ADAL
            // - openid and profile scope adds profile information to the id_token
            // - login_hint provides the expected user name
            if (upn) {
                config.extraQueryParameters = "scope=openid+profile&login_hint=" + encodeURIComponent(upn);
            } else {
                config.extraQueryParameters = "scope=openid+profile";
            }

            let authContext = new AuthenticationContext(config);

            // See if there's a cached user and it matches the expected user
            let user = authContext.getCachedUser();
            if (user) {
                if (user.userName !== upn) {
                    // User doesn't match, clear the cache
                    authContext.clearCache();
                }
            }

            // Get the id token (which is the access token for resource = clientId)
            let token = authContext.getCachedToken(config.clientId);
            if (token) {
                showProfileInformation(token);
            } else {
                // No token, or token is expired
                authContext._renewIdToken(function (err, idToken) {
                    if (err) {
                        console.log("Renewal failed: " + err);

                        // Failed to get the token silently; show the login button
                        $("#btnLogin").css({ display: "" });

                        // You could attempt to launch the login popup here, but in browsers this could be blocked by
                        // a popup blocker, in which case the login attempt will fail with the reason FailedToOpenWindow.
                    } else {
                        showProfileInformation(idToken);
                    }
                });
            }
        }

        // Login to Azure AD
        function login() {
            $("#divError").text("").css({ display: "none" });
            $("#divProfile").css({ display: "none" });

            microsoftTeams.authentication.authenticate({
                url: window.location.origin + "/AuthStart",
                width: 600,
                height: 535,
                successCallback: function (result) {
                    // AuthenticationContext is a singleton
                    let authContext = new AuthenticationContext();
                    let idToken = authContext.getCachedToken(config.clientId);
                    if (idToken) {
                        showProfileInformation(idToken);
                    } else {
                        console.error("Error getting cached id token. This should never happen.");
                        // At this point we have to get the user involved, so show the login button
                        $("#btnLogin").css({ display: "" });
                    };
                },
                failureCallback: function (reason) {
                    console.log("Login failed: " + reason);
                    if (reason === "CancelledByUser" || reason === "FailedToOpenWindow") {
                        console.log("Login was blocked by popup blocker or canceled by user.");
                    }
                    // At this point we have to get the user involved, so show the login button
                    $("#btnLogin").css({ display: "" });

                    $("#divError").text(reason).css({ display: "" });
                    $("#divProfile").css({ display: "none" });
                }
            });
        }

        // Get the user's profile information from the id token
        function showProfileInformation(idToken) {
            $.ajax({
                url: window.location.origin + "/Home/ValidateToken?validToken=" + idToken,
                beforeSend: function (request) {
                    request.setRequestHeader("Authorization", "Bearer " + idToken);
                },
                success: function (token) {
                    var token = JSON.parse(token);
                    $("#profileDisplayName").text(token.name);
                    $("#profileUpn").text(token.upn);
                    $("#profileObjectId").text(token.oid);
                    $("#divProfile").css({ display: "" });
                    $("#divError").css({ display: "none" });
                    microsoftTeams.settings.setValidityState(true);

                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log("textStatus: " + textStatus + ", errorThrown:" + errorThrown);
                    $("#divError").text(errorThrown).css({ display: "" });
                    $("#divProfile").css({ display: "none" });
                },
            });
        }

        microsoftTeams.initialize();
        microsoftTeams.settings.registerOnSaveHandler(function (saveEvent) {
            var radios = document.getElementsByName('notificationType');

            microsoftTeams.settings.setSettings({
                entityId: 'Silent Authentication',
                contentUrl: window.location.origin + "/Home/Index",
                configName: 'SilentAuthentication'
            });
            saveEvent.notifySuccess();
        });
    </script>
</body>
</html>

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <table>
        <tr>
            <td id="greetingMsgSetup">
                
            </td>
        </tr>
    </table>
</div>
<script type="text/javascript">

    microsoftTeams.initialize();
    window.onload = function () {

        if (localStorage.getItem("displayName") !== null) {
            document.getElementById("greetingMsgSetup").innerHTML = `Welcome ${localStorage.getItem("displayName")}...`;
        }
        else {
            document.getElementById("greetingMsgSetup").innerHTML = `Welcome...`
        }
    };
</script>

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Views/Home/SetUp.cshtml
<div>
    <table>
        <tr>
            <td id="greetingMsgSetup">
               
            </td>
        </tr>
    </table>
</div>

<script src="@("https://unpkg.com/@microsoft/teams-js@1.3.3/dist/MicrosoftTeams.min.js")"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha384-VC7EHu0lDzZyFfmjTPJq+DFyIn8TUGAJbEtpXquazFVr00Q/OOx//RjiZ9yU9+9m" crossorigin="anonymous"></script>
<script src="https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js" integrity="sha384-mhp2E+BLMiZLe7rDIzj19WjgXJeI32NkPvrvvZBrMi5IvWup/1NUfS5xuYN5S3VT" crossorigin="anonymous"></script>
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.17/js/adal.min.js" integrity="sha384-BIOS/65fbAsb2XiCCSTlZSTTl0ZgqkOU522dpyk5meOnN2EOQ3uH+QpqEtoAtmBn" crossorigin="anonymous"></script>
<script type="text/javascript">

    microsoftTeams.initialize();
    console.log(localStorage.getItem("displayName"));
    window.onload = function () {
       
        document.getElementById("greetingMsgSetup").innerHTML = `Welcome ${localStorage.getItem("displayName")}...`;
    };
</script>

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Views/Home/SilentConfigureTab.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>
    This sample demonstrates silent authentication in a Microsoft Teams tab.
</p>
<p>
    The tab will try to get an id token for the user silently, validate the token and show the profile information decoded from the token.
    The "Login" button will appear only if silent authentication failed.
</p>

<!-- Login button -->
<button id="btnLogin" onclick="login()" style="display: none">Login to Azure AD</button>

<!-- Result -->
<p>
    <div id="divError" style="display: none"></div>
    <div id="divProfile" style="display: none">
        <div><b>Name:</b> <span id="profileDisplayName" /></div>
        <div><b>UPN:</b> <span id="profileUpn" /></div>
        <div><b>Object id:</b> <span id="profileObjectId" /></div>
    </div>
    <div style="height: 50px">
    </div>
    <div id="divSilentSignOut" style="display: none">
        <button onclick="SilentLogout()">Sign Out</button>
    </div>
</p>
<script src="~/library/MicrosoftTeams.min.js"></script>
<script type="text/javascript">
        microsoftTeams.initialize();

        // ADAL.js configuration
        let config = {
            clientId: '@ViewBag.ClientId',
            redirectUri: window.location.origin + "/SilentAuthEnd",       // This should be in the list of redirect uris for the AAD app
            cacheLocation: "localStorage",
            navigateToLoginRequestUrl: false,
        };

        //localStorage.setItem("Client", config.clientId)
        let upn = undefined;
        microsoftTeams.getContext(function (context) {
            upn = context.upn;
            loadData(upn);
        });

        // Loads data for the given user
        function loadData(upn) {
            // Setup extra query parameters for ADAL
            // - openid and profile scope adds profile information to the id_token
            // - login_hint provides the expected user name
            if (upn) {
                config.extraQueryParameters = "scope=openid+profile&login_hint=" + encodeURIComponent(upn);
            } else {
                config.extraQueryParameters = "scope=openid+profile";
            }

            let authContext = new AuthenticationContext(config);

            // See if there's a cached user and it matches the expected user
            let user = authContext.getCachedUser();
            if (user) {
                if (user.userName !== upn) {
                    // User doesn't match, clear the cache
                    authContext.clearCache();
                }
            }

            // Get the id token (which is the access token for resource = clientId)
            let token = authContext.getCachedToken(config.clientId);
            if (token) {
                showProfileInformation(token);
            } else {
                // No token, or token is expired
                authContext._renewIdToken(function (err, idToken) {
                    if (err) {
                        console.log("Renewal failed: " + err);

                        // Failed to get the token silently; show the login button
                        $("#btnLogin").css({ display: "" });

                        // You could attempt to launch the login popup here, but in browsers this could be blocked by
                        // a popup blocker, in which case the login attempt will fail with the reason FailedToOpenWindow.
                    } else {
                        showProfileInformation(idToken);
                    }
                });
            }
        }

        // Login to Azure AD
        function login() {
            $("#divError").text("").css({ display: "none" });
            $("#divProfile").css({ display: "none" });
            $("#divSilentSignOut").css({ display: "none" });


            microsoftTeams.authentication.authenticate({
                url: window.location.origin + "/SilentAuthStart",
                width: 600,
                height: 535,
                successCallback: function (result) {
                    // AuthenticationContext is a singleton
                    let authContext = new AuthenticationContext();
                    let idToken = authContext.getCachedToken(config.clientId);
                    if (idToken) {
                        showProfileInformation(idToken);
                    } else {
                        console.error("Error getting cached id token. This should never happen.");
                        // At this point we have to get the user involved, so show the login button
                        $("#btnLogin").css({ display: "" });
                    };
                },
                failureCallback: function (reason) {
                    console.log("Login failed: " + reason);
                    if (reason === "CancelledByUser" || reason === "FailedToOpenWindow") {
                        console.log("Login was blocked by popup blocker or canceled by user.");
                    }
                    // At this point we have to get the user involved, so show the login button
                    $("#btnLogin").css({ display: "" });

                    $("#divError").text(reason).css({ display: "" });
                    $("#divProfile").css({ display: "none" });
                    $("#divSilentSignOut").css({ display: "none" });
                }
            });
        }

        // Get the user's profile information from the id token
        function showProfileInformation(idToken) {
            $.ajax({
                url: window.location.origin + "/Home/ValidateToken?validToken=" + idToken,
                beforeSend: function (request) {
                    request.setRequestHeader("Authorization", "Bearer " + idToken);
                },
                success: function (token) {
                    var token = JSON.parse(token);
                    $("#profileDisplayName").text(token.name);
                    $("#profileUpn").text(token.upn);
                    $("#profileObjectId").text(token.oid);
                    $("#divProfile").css({ display: "" });
                    $("#divSilentSignOut").css({ display: "" });
                    $("#divError").css({ display: "none" });
                    microsoftTeams.settings.setValidityState(true);

                    localStorage.setItem("displayName", token.name);

                },
                error: function (xhr, textStatus, errorThrown) {
                    console.log("textStatus: " + textStatus + ", errorThrown:" + errorThrown);
                    $("#divError").text(errorThrown).css({ display: "" });
                    $("#divProfile").css({ display: "none" });
                    $("#divSilentSignOut").css({ display: "none" });
                },
            });
        }

        microsoftTeams.initialize();
        microsoftTeams.settings.registerOnSaveHandler(function (saveEvent) {
            var radios = document.getElementsByName('notificationType');

            microsoftTeams.settings.setSettings({
                entityId: 'Silent Authentication',
                contentUrl: window.location.origin + "/Home/Index",
                configName: 'SilentAuthentication'
            });
            saveEvent.notifySuccess();
        });

    function SilentLogout() {
        localStorage.clear();
        window.location.href = "@Url.Action("ChooseAuth", "Home")";
    }


</script>

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Views/Home/SimpleConfigureTab.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <div>
        <span>To add a Tab please Sign In:</span>
        <!-- Login button -->
        <button onclick="loginV1()">Sign In</button>
    </div>

</div>

<script type="text/javascript">

    microsoftTeams.initialize();

    function loginV1() {
        login(window.location.origin + "/SimpleAuthStart");
    }

    function login(url) {
        microsoftTeams.authentication.authenticate({
            url: url,
            width: 600,
            height: 535,
            successCallback: function (result) {
                console.log("Login succeeded: " + result);

                let data = localStorage.getItem(result);
                localStorage.removeItem(result);

                let tokenResult = JSON.parse(data);
                getUserProfile(tokenResult.accessToken);

                window.location.href = "@Url.Action("SimpleSuccess", "Authentication")";
            },
            failureCallback: function (reason) {
                console.log("Login failed: " + reason);
                handleAuthError(reason);
                window.location.href = "@Url.Action("SimpleFailed", "Authentication")";
            }
        });
    }

   //Get the user's profile information from Microsoft Graph
    function getUserProfile(accessToken) {
        $.ajax({
            url: "https://graph.microsoft.com/v1.0/me/",
            beforeSend: function (request) {
                request.setRequestHeader("Authorization", "Bearer " + accessToken);
            },
            success: function (profile) {
                localStorage.setItem("displayName", profile.displayName);
                console.log("User name is " + profile.displayName);
            },
            error: function (xhr, textStatus, errorThrown) {
                console.log("textStatus: " + textStatus + ", errorThrown:" + errorThrown);
            },
        });
    }
</script>

Microsoft-Teams-Samples/samples/tab-channel-group-config-page-auth/csharp/ConfigTabAuthentication/Views/Home/SimpleSetUp.cshtml
<div>
    <table>
        <tr>
            <td id="greetingMsgSetup">
            </td>
        </tr>
    </table>
</div>

<script src="@("https://unpkg.com/@microsoft/teams-js@1.3.3/dist/MicrosoftTeams.min.js")"></script>
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha384-VC7EHu0lDzZyFfmjTPJq+DFyIn8TUGAJbEtpXquazFVr00Q/OOx//RjiZ9yU9+9m" crossorigin="anonymous"></script>
<script src="https://statics.teams.cdn.office.net/sdk/v1.6.0/js/MicrosoftTeams.min.js" integrity="sha384-mhp2E+BLMiZLe7rDIzj19WjgXJeI32NkPvrvvZBrMi5IvWup/1NUfS5xuYN5S3VT" crossorigin="anonymous"></script>
<script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.17/js/adal.min.js" integrity="sha384-BIOS/65fbAsb2XiCCSTlZSTTl0ZgqkOU522dpyk5meOnN2EOQ3uH+QpqEtoAtmBn" crossorigin="anonymous"></script>
<script type="text/javascript">

    microsoftTeams.initialize();
    console.log(localStorage.getItem("displayName"));
    window.onload = function () {

        document.getElementById("greetingMsgSetup").innerHTML = `Welcome ${localStorage.getItem("displayName")}...`;
    };
</script>